---
queue: aspect-default
bazel:
  rcfiles:
      - ".aspect/bazelrc/ci.sourcegraph.bazelrc"
env:
    CI: "true"
    PGUSER: postgres
    PGPASSWORD: postgres
    PGDATABASE: postgres
    PGSSLMODE: disable
    REDIS_CACHE_ENDPOINT: ":6379"
    GIT_PAGER: ''
    DISPLAY: ":99"
tasks:
    # Checks that the branch is current
    branch_freshness:
        # Rebase PR changes on main, to avoid churning the repository cache
        update_strategy: rebase
    # Checks that BUILD file content is up-to-date with sources
    # gazelle:
    # Checks that all tests are passing
    test:
      targets:
          - //...
          - //testing:grpc_backend_integration_test
          - //testing:codeintel_integration_test
