---
bazel:
  rcfiles:
    - ".aspect/bazelrc/ci.sourcegraph.bazelrc"
env:
  REDIS_CACHE_ENDPOINT: ":6379"
  GIT_PAGER: ""
# Temporary work-around to resolve a slow post task agent health check
observability: false
tasks:
  - checkout:
      update_strategy: rebase
  # Checks that BUILD files are formatted
  - buildifier:
      queue: aspect-small
      timeout_in_minutes: 3
  # Checks that BUILD file content is up-to-date with sources
  - gazelle:
      queue: aspect-small
      target: //:configure
      fix_target: //:configure
      timeout_in_minutes: 5
  # Checks that all tests are passing
  - test:
      targets:
        - //...
        # exclude testing as it is executed in a seperate job
        - -//testing/...
      artifact_paths:
        - build_event_log.bin
        - execution_log.zstd
  - test:
      name: Integration/E2E
      targets:
        - //testing/...
        # This target should only really run when on main which we aren't handling. For the time being while we
        # evaluate Aspect Workflows it is ok
        # TODO(burmudar): Let this only run on main branch
        - //testing:codeintel_integration_test
      artifact_paths:
        - build_event_log.bin
        - execution_log.zstd
  - delivery:
      auto_deliver: true
      icon: 'ship'
      stamp_flags: ['--stamp', '--workspace_status_command=./dev/bazel_stamp_vars.sh']
      rules:
        - deliverable: 'attr(tags, "docs-deliverable", //doc/...)'
          condition:
            only_on_change: true
            branches:
              - '^main$'
        - deliverable: 'attr(tags, "msp-deliverable", //...)'
          condition:
            branches:
              - '^main$'
  - finalization:
      queue: aspect-small
