---
- labels:
    job: frontend
  targets:
    # frontend
    - host.docker.internal:6063
- labels:
    job: gitserver
  targets:
    # gitserver
    - host.docker.internal:6068
- labels:
    job: searcher
  targets:
    # searcher
    - host.docker.internal:6069
- labels:
    job: symbols
  targets:
    # symbols
    - host.docker.internal:6071
- labels:
    job: repo-updater
  targets:
    # repo-updater
    - host.docker.internal:6074
- labels:
    job: query-runner
  targets:
    # query-runner
    - host.docker.internal:6067
- labels:
    job: zoekt-indexserver
  targets:
    # zoekt-indexserver
    - host.docker.internal:6072
- labels:
    job: precise-code-intel-bundle-manager
  targets:
    # precise-code-intel-bundle-manager
    - host.docker.internal:6087
- labels:
    job: precise-code-intel-worker
  targets:
    # precise-code-intel-worker
    - host.docker.internal:6088
- labels:
    job: precise-code-intel-indexer
  targets:
    # precise-code-intel-indexer
    - host.docker.internal:6089
- labels:
    job: postgres_exporter
  targets:
    # postgres exporter
    - host.docker.internal:9187
- labels:
    job: replacer
  targets:
    # replacer
    - host.docker.internal:6076
