---
- labels:
    job: sourcegraph-frontend
  targets:
    # frontend
    - host.docker.internal:6063
- labels:
    job: gitserver
  targets:
    # gitserver 1
    - host.docker.internal:3551
    # gitserver 2
    - host.docker.internal:3552
- labels:
    job: searcher
  targets:
    # searcher
    - host.docker.internal:6069
- labels:
    job: symbols
  targets:
    # symbols
    - host.docker.internal:6071
- labels:
    job: repo-updater
  targets:
    # repo-updater
    - host.docker.internal:6074
- labels:
    job: zoekt-indexserver
  targets:
    # zoekt-indexserver
    - host.docker.internal:6072
    - host.docker.internal:6073
- labels:
    job: zoekt-webserver
  targets:
    # zoekt-webserver
    - host.docker.internal:3070
    - host.docker.internal:3071
- labels:
    job: precise-code-intel-worker
  targets:
    # precise-code-intel-worker
    - host.docker.internal:6088
- labels:
    job: worker
  targets:
    # worker
    - host.docker.internal:6089
- labels:
    job: worker-executors
  targets:
    # worker
    - host.docker.internal:6996
- labels:
    job: postgres_exporter
  targets:
    # postgres exporter
    - host.docker.internal:9187
- labels:
    job: otel-collector
  targets:
    # opentelemetry collector
    - host.docker.internal:8888
- labels:
    job: embeddings
  targets:
    # embeddings
    - host.docker.internal:6099
- labels:
    job: cody-gateway
  targets:
    # cody gateway
    - host.docker.internal:6098
- labels:
    job: telemetry-gateway
  targets:
    # cody gateway
    - host.docker.internal:6080
