language: go
services:
- docker
go:
- 1.13.x
go_import_path: github.com/sourcegraph/src-cli
install:
- go get -d -t ./...
- go test -i ./...
script:
- cd $TRAVIS_BUILD_DIR
- go test -race -v ./...
env:
  global:
  - secure: eFuG5PSCXNz0i4Knic0wVmTko+O/epoLWpDtDs7jGHo3UD0JIukDTeIoHRPF56LEF3ZmfJWarc0XWZRSUmtn2EYydvCrTlroXLe6lfiFL/ctH0CWpArCp5xHQKVqKk+h6F53hAva3o181PfnFtk58H/xgj2jo8sANbqXricnL5aT34RVje85483poL2RLmd2WiYVqDqeGdkg7DaorpJra1mFvOCmInrbMpexpomJKmpCbxzrdvUmvRE9bDWLHctgvWL6bVTsQNzUN0zh6AIfT0FuFmiwjVlD5d4Bo10jUucg1qs4gglHneplPMoQb3dW7reeE1hIjuZSjXmDZKwYaonpuy8lsEJTEZpo18obYfRP9fjJZJb71rQ/sjbAd2EEV84r13k4JcprUp4uFd/LgUpHNwyRxnm2bKneHSpf9eb0D+A6Kzxkix/vSJeH8G/pHc07mYtf1rqMG57eVeeVinAFbGsvmggQfFGXupW3c48VYS6TTUmcUv0B7jiDHEdFG1zRXElX48S6HJnhI4531jxbEsvgBt63sR5wH5dZv++VodzznwjaJ4LJv+bxZEtswhNA/nzxGCk9vNDkhPxpS531mNAyfV2ewJ81QW94BuWh0dTfo6gVypCS/2xI8L2I2sqs5vk2iCr51WJDL79yLXRP6QhXLcr8jgDpBQMNbpE=
  - secure: QTlZyxez8zpQtcpZL4RrNLgoFp1ASCvMwnc5tzXcOPXTOHrFEcpwZxhgHUzIKLNK7mqFLvTNgd0AZLV09AcH06byTC14Nv4BVhXSl1gyG610PSvTbdCRD+D8U+2LYqy2DyhT5jSwmoP9vYV+YL5ujDgSNPSVMj7MsD8Oi1EqVffZI/7PuEXvyyJum65jjUVJBjH937aUyoWoxSPHYkMOHuGVJPtHriOCjSKJhrlUZOjLgX9dJQMukSKHP8UD4xzw8TkPeUqh0KCDSYV12Irvy4PQwUbkwrJoSCd+N8yGpwboiTBWGatKTYZ4+rY3GgCMtwJ1c1csTlV99E+QHLFBHOVKx5gZKaJo94/YjvOFg9wbJ8JfH2jARJs+0Tx3diPMO0j8EP4bisorptIcMTvZAeo2QbsPTR+EwCR3/eD5qF+c+eWK9dxSvzIbOitgsptxMM24hocPACE4U2EjJE+n8gmjZApm44aFejEGA2CyCOgNsKZlIsqNbe4bdrLiTIAWNqpTwvQ6ab/G1nWhinFqF3SAhRjsKjU76eVI/I9AmmAqdp2ixVtzK//9NJ5DtyM9bsCpizZFfg4AUXQCe3GARxMB0rN7DOiMnK9ANBHtsSJqf08JUuxc3tA7zLaRg53Nw4P90FVi18xrPEx4eI2+wmNih7FpEUsyHgze8sU68Oc=
after_success:
- test -n "$TRAVIS_TAG" && echo "${DOCKER_PASSWORD}" | docker login -u=sourcegraphci --password-stdin
deploy:
- provider: script
  script:
  - curl -sL https://git.io/goreleaser | bash
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_TAG != latest"
