[package]
name = "scip-syntax"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "scip-syntax"

[dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
insta = "1.34.0"
indicatif = "0.17.7"
colored = "2.0.4"

protobuf = { workspace = true }
scip = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
lazy_static = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
string-interner = { workspace = true }
walkdir = { workspace = true }

syntax-analysis = { path = "../syntax-analysis" }
tree-sitter-all-languages = { path = "../tree-sitter-all-languages" }
tar = "0.4.40"
