[package]
name = "scip-syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
itertools.workspace = true
protobuf.workspace = true
scip.workspace = true
tree-sitter.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true

scip-macros = { path = "../scip-macros" }
scip-treesitter = { path = "../scip-treesitter" }
scip-treesitter-languages = { path = "../scip-treesitter-languages" }

rustc-hash = "1.1.0"
insta = "*"
once_cell = "1.17.1"
bitvec = "1.0.1"
regex = "1"
