apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-executor-codeintel
  namespace: default
spec:
  selector:
    matchLabels:
      app: sg-executor-codeintel
  template:
    metadata:
      namespace: default
      labels:
        app: sg-executor-codeintel
    spec:
      # For development purposes - lets the executor pod use the namespace of the host system instead of creating a new one.
      hostNetwork: true
      serviceAccountName: sg-executor-service-account
      containers:
        - name: sg-executor-codeintel
          image: executor-kubernetes:candidate
          imagePullPolicy: IfNotPresent
          env:
            - name: EXECUTOR_FRONTEND_URL
              # For development purposes. We usually run Sourcegraph in Docker.
              value: http://host.docker.internal:3082
            - name: EXECUTOR_FRONTEND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: executor-frontend-password
                  key: EXECUTOR_FRONTEND_PASSWORD
            - name: EXECUTOR_QUEUE_NAME
              value: codeintel
            # Each job will consume 5Gi of memory. Need to make sure not to consume the whole node's memory.
            - name: EXECUTOR_MAXIMUM_NUM_JOBS
              value: "1"
            - name: SRC_LOG_LEVEL
              value: dbug
            - name: SRC_LOG_FORMAT
              value: condensed
            - name: SRC_TRACE_LOG
              value: "false"
            - name: EXECUTOR_KUBERNETES_RESOURCE_REQUEST_MEMORY
              value: 5Gi
            # Match the name of the volume in executor-batches.PersistentVolumeClaim.yml.
            - name: EXECUTOR_KUBERNETES_PERSISTENCE_VOLUME_NAME
              value: sg-executor-codeintel-pvc
              # Since the host is 'host.docker.internal', this needs to be true.
            - name: EXECUTOR_DOCKER_ADD_HOST_GATEWAY
              value: "true"
            # Ensure that the job pods are scheduled on the same node as the executor pod.
            - name: EXECUTOR_KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Useful for debugging.
#            - name: KUBERNETES_KEEP_JOBS
#              value: "true"
#            - name: EXECUTOR_KEEP_WORKSPACES
#              value: "true"
            # Check executor-batches.Role.yml to ensure the correct rules are enabled.
#            - name: KUBERNETES_SINGLE_JOB_POD
#              value: "true"
            # Check executor-batches.Role.yml to ensure the correct rules are enabled.
#            - name: KUBERNETES_JOB_VOLUME_TYPE
#              value: "pvc"
          volumeMounts:
            - mountPath: /data
              name: sg-executor-codeintel-volume
      volumes:
        - name: sg-executor-codeintel-volume
          persistentVolumeClaim:
            claimName: sg-executor-codeintel-pvc
