env:
  POSTGRES_HOST: localhost
  PGPASSWORD: sourcegraph
  PGUSER: sourcegraph
  SRC_GIT_SERVER_1: 127.0.0.1:3501
  SRC_GIT_SERVER_2: 127.0.0.1:3502
  SRC_GIT_SERVERS: 127.0.0.1:3501 127.0.0.1:3502
  SRC_PROF_SERVICES: |
    [
      { "Name": "frontend", "Host": "127.0.0.1:6063" },
      { "Name": "enterprise-frontend", "Host": "127.0.0.1:6063" },
      { "Name": "gitserver-0", "Host": "127.0.0.1:3551" },
      { "Name": "gitserver-1", "Host": "127.0.0.1:3552" },
      { "Name": "searcher", "Host": "127.0.0.1:6069" },
      { "Name": "symbols", "Host": "127.0.0.1:6071" },
      { "Name": "repo-updater", "Host": "127.0.0.1:6074" },
      { "Name": "enterprise-repo-updater", "Host": "127.0.0.1:6074" },
      { "Name": "precise-code-intel-worker", "Host": "127.0.0.1:6088" },
      { "Name": "worker", "Host": "127.0.0.1:6089" },
      { "Name": "enterprise-worker", "Host": "127.0.0.1:6089" },
      { "Name": "executor-codeintel", "Host": "127.0.0.1:6092" },
      { "Name": "executor-batches", "Host": "127.0.0.1:6093" },
      { "Name": "zoekt-indexserver-0", "Host": "127.0.0.1:6072" },
      { "Name": "zoekt-indexserver-1", "Host": "127.0.0.1:6073" },
      { "Name": "zoekt-webserver-0", "Host": "127.0.0.1:3070", "DefaultPath": "/debug/requests/" },
      { "Name": "zoekt-webserver-1", "Host": "127.0.0.1:3071", "DefaultPath": "/debug/requests/" }
    ]

commands:
  gitserver-template: &gitserver_template # This is copied from the original `gitserver` definition
    cmd: .bin/gitserver
    install: |
      if [ -n "$DELVE" ]; then
        export GCFLAGS='all=-N -l'
      fi
      go build -gcflags="$GCFLAGS" -o .bin/gitserver github.com/sourcegraph/sourcegraph/cmd/gitserver
    checkBinary: .bin/gitserver
    env: &gitserverenv
      HOSTNAME: 127.0.0.1:3178
    watch:
      - lib
      - internal
      - cmd/gitserver

  gitserver-0:
    <<: *gitserver_template
    env:
      <<: *gitserverenv
      HOSTNAME: 127.0.0.1:3501
      GITSERVER_ADDR: 127.0.0.1:3501
      SRC_REPOS_DIR: $HOME/.sourcegraph/repos_1

  gitserver-1:
    <<: *gitserver_template
    env:
      <<: *gitserverenv
      HOSTNAME: 127.0.0.1:3502
      GITSERVER_ADDR: 127.0.0.1:3502
      SRC_REPOS_DIR: $HOME/.sourcegraph/repos_2

commandsets:
  double-gitservers:
    requiresDevPrivate: true
    checks:
      - docker
      - redis
      - postgres
      - git
    commands:
      - enterprise-frontend
      - enterprise-worker
      - enterprise-repo-updater
      - enterprise-web
      - gitserver-0
      - gitserver-1
      - searcher
      - symbols
      - caddy
      - docsite
      - syntax-highlighter
      - github-proxy
      - zoekt-indexserver-0
      - zoekt-indexserver-1
      - zoekt-webserver-0
      - zoekt-webserver-1
