[package]
name = "syntect_server"
version = "1.0.1"
authors = [
    "TJ DeVries <devries.timothyj@gmail.com>",
    "Stephen Gutekanst <stephen.gutekanst@gmail.com>"
]
edition = "2018"
license = "MIT"

[dependencies]
syntect = { git = "https://github.com/sourcegraph/syntect" }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sg-syntax = { path = "./crates/sg-syntax" }
rustyline = "9.1.2"
scip = { git = "https://github.com/sourcegraph/scip" }

[workspace]
members = [
    "crates/sg-macros",
    "crates/sg-syntax",
]
