[package]
name = "syntect_server"
version = "1.0.1"
authors = [
    "TJ DeVries <devries.timothyj@gmail.com>",
    "Stephen Gutekanst <stephen.gutekanst@gmail.com>"
]
edition = "2021"
license = "MIT"

[dependencies]
rocket.workspace = true
scip.workspace = true
serde.workspace = true
serde_json.workspace = true
syntect.workspace = true

rustyline = "9.1.2"

sg-syntax = { path = "./crates/sg-syntax" }
scip-treesitter-languages = { path = "./crates/scip-treesitter-languages" }

[workspace]
members = [
    "crates/sg-syntax",

    # later, these will be pulled out to a separate repo
    "crates/scip-macros",
    "crates/scip-syntax",
    "crates/scip-treesitter",
    "crates/scip-treesitter-languages",
    # "crates/ctags",
]

[workspace.dependencies]
anyhow = "1"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syntect = { git = "https://github.com/sourcegraph/syntect", branch = "main" }
tree-sitter = "0.20.9"
tree-sitter-highlight = "0.20"

scip = { git = "https://github.com/sourcegraph/scip", branch = "main" }
protobuf = "3"

[profile.release]
# Enabled debug symbols in release build, so if we have a crash
# we can inspect the coredump.
debug = true
