---
- labels:
    job: frontend
  targets:
    # frontend
    - 127.0.0.1:6063
- labels:
    job: gitserver
  targets:
    # gitserver
    - 127.0.0.1:6068
- labels:
    job: searcher
  targets:
    # searcher
    - 127.0.0.1:6069
- labels:
    job: symbols
  targets:
    # symbols
    - 127.0.0.1:6071
- labels:
    job: repo-updater
  targets:
    # repo-updater
    - 127.0.0.1:6074
- labels:
    job: query-runner
  targets:
    # query-runner
    - 127.0.0.1:6067
- labels:
    job: zoekt-indexserver
  targets:
    # zoekt-indexserver
    - 127.0.0.1:6072
- labels:
    job: precise-code-intel-bundle-manager
  targets:
    # precise-code-intel-bundle-manager
    - 127.0.0.1:6087
- labels:
    job: precise-code-intel-worker
  targets:
    # precise-code-intel-worker
    - 127.0.0.1:6088
- labels:
    job: postgres_exporter
  targets:
    # postgres exporter
    - 127.0.0.1:9187
- labels:
    job: replacer
  targets:
    # replacer
    - 127.0.0.1:6076
