[package]
name = "syntax-analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
itertools.workspace = true
lazy_static.workspace = true
paste.workspace = true
protobuf.workspace = true
scip.workspace = true
serde.workspace = true
serde_json.workspace = true
syntect.workspace = true
tree-sitter.workspace = true
tree-sitter-highlight.workspace = true
walkdir.workspace = true
camino.workspace = true

tree-sitter-all-languages = { path = "../tree-sitter-all-languages" }

rustc-hash = "1.1.0"
insta = "*"
once_cell = "1.17.1"
bitvec = "1.0.1"
regex = "1"
id-arena = "2.2.1"
string-interner = "0.14.0"
if_chain = "1.0.2"
base64 = "0.13.0"

[dev-dependencies]
insta.workspace = true
pretty_assertions = "1.2.1"
