[package]
name = "scip-treesitter-languages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.0"
paste = "1.0.6"

scip-macros = { path = "../scip-macros" }

scip.workspace = true

tree-sitter.workspace = true
tree-sitter-highlight = "0.20"

tree-sitter-c = "0.20.2"
tree-sitter-c-sharp = "0.20.0"
tree-sitter-cpp = "0.20.0"
tree-sitter-go = "0.19.1"
tree-sitter-java = "0.20.0"
tree-sitter-javascript = "0.20.0"
tree-sitter-jsonnet = { git = "https://github.com/sourcegraph/tree-sitter-jsonnet" }
tree-sitter-python = "0.20.2"
tree-sitter-perl = { git = "https://github.com/sourcegraph/tree-sitter-perl" }
tree-sitter-pod = { git = "https://github.com/sourcegraph/tree-sitter-pod" }
tree-sitter-ruby = "0.20.0"
tree-sitter-rust = "0.20.3"
tree-sitter-typescript = "0.20.2"
tree-sitter-xlsg = { git = "https://github.com/sourcegraph/tree-sitter-xlsg" }

# Using a fork of tree-sitter-scala because upstream Rust crate didn't compile.
tree-sitter-scala = { git = "https://github.com/sourcegraph/tree-sitter-scala" }

# As of 2022 Apr 06, the upstream crate seems to have paused development,
# and it relies to tree-sitter 0.19.x creating a type mismatch. So depend
# on our own fork.
tree-sitter-sql = { git = "https://github.com/sourcegraph/tree-sitter-sql" }
