groups:
  - name: replacer
    rules:
      - record: alert_count
        labels:
          service_name: replacer
          level: warning
          name: frontend_internal_errors
          description: 'replacer: 5+ non-200 responses from the frontend-internal API over 5m'
        expr: >-
          clamp_max(clamp_min(floor(
          (increase(src_frontend_internal_request_duration_seconds_count{job="replacer",code!~"2.."}[5m]) / 5) OR on() vector(0)
          ), 0), 1) OR on() vector(1)
