name: notify-batchers-team
on:
  issues:
    types: [opened]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-create-comment@v1
        if: (contains(github.event.issue.body, 'batch') && !contains(github.event.issue.labels.*.name, 'team/batchers'))
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hey, @sourcegraph/batchers (@eseliger @courier-new @adeola-ak @BolajiOlajide @Piszmog @st0nebraker @ryphil @chrispine @danielmarquespt) - we have been mentioned. Let's take a look.
