# See dev/buildchecker/README.md
name: buildchecker
on:
  schedule:
  - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run:
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest

    # secrets for this workflow are configured in the 'autobuildsherrif' environment.
    # 'autobuildsherrif' was the original name of the 'buildchecker' tool - GitHub does
    # not provide a simple way to do a rename, so we leave it as is for now.
    environment: autobuildsherrif

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with: { go-version: '1.21' }
      - uses: actions/setup-node@v4
      - run: exit 1 #./dev/buildchecker/run-check.sh
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOBUILDSHERRIF_GITHUB_TOKEN }}
          BUILDKITE_TOKEN: ${{ secrets.AUTOBUILDSHERRIF_BUILDKITE_TOKEN }}
          SLACK_ANNOUNCE_WEBHOOK: ${{ secrets.AUTOBUILDSHERRIF_SLACK_WEBHOOK }}
          SLACK_DEBUG_WEBHOOK: ${{ secrets.AUTOBUILDSHERRIF_SLACK_DEBUG_WEBHOOK }}
          SLACK_TOKEN: ${{ secrets.AUTOBUILDSHERRIF_SLACK_TOKEN }}
      - name: Report failure to Sentry
        if: ${{ failure() }}
        uses: ./.github/actions/report-failure
        with:
          dsn: "${{ secrets.SENTRY_DEV_INFRA_DSN}}"
          repo: "${{ github.repository }}"
          branch: "${{ github.ref_name }}"
          run_id: "${{ github.run_id }}"
          workflow_name: "${{ github.workflow }}"
          job_name: "${{ job.job }}"
