name: codenotify
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  codenotify:
    runs-on: ubuntu-latest
    name: codenotify
    if: ${{ !startsWith(github.head_ref, 'contractors/' )}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: sourcegraph/codenotify@v0.6.2
        with:
          filename: 'CODENOTIFY'
          subscriber-threshold: '15'
        env:
          GITHUB_TOKEN: ${{ secrets.CODENOTIFY_GITHUB_TOKEN }}
      - uses: sourcegraph/codenotify@v0.6.2
        continue-on-error: true
        with:
          filename: 'OWNERS'
          subscriber-threshold: '15'
        env:
          GITHUB_TOKEN: ${{ secrets.CODENOTIFY_GITHUB_TOKEN }}
