name: codenotify
on: [pull_request]

jobs:
  codenotify:
    runs-on: ubuntu-latest
    name: codenotify
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: sourcegraph/codenotify@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
