name: Release 4.0 protection
on:
  pull_request:
    types: [ closed, edited, opened, synchronize, ready_for_review, labeled, unlabeled]
    branches: 
      # only run on branches targeting the `main` branch.
      - main

jobs:
  protect-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check date and labels
        id: check-date-and-labels
        run: |
          has_label="${{contains(github.event.pull_request.labels.*.name, 'must-go-in-4.0')}}"
          today=$(date +'%Y%m%d%H%M')
          dday="202209090000"

          if [ "$today" -gt "$dday" ]; then
            if [ "$has_label" = "true" ]; then
              echo "âœ… Label 'must-go-in-4.0' is present"
              exit 0
            else 
              echo "âŒ Label 'must-go-in-4.0' is absent"
              exit 1
            fi
          else
            echo "ğŸ“… Not enabled, we're not yet on 2022-09-09 and 4.0 has not been released." 
            exit 0
          fi
