name: "Notify users based on issue labels"

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: felixfbecker/issue-label-notification-action@57b8a1f93c7951ce8af6cce8c6c90ae35a51c2e0
          with:
             token: "${{ secrets.LABELER_GITHUB_TOKEN }}"
             edit_body: true
             message: /cc {recipients}
             recipients: |
                  team/integrations=@muratsu @jjinnii @ryankscott
                  team/growth=@muratsu @a-bergevin
                  team/cloud=@sourcegraph/cloud
                  team/search-product=@benvenker @lguychard
                  team/search-core=@sourcegraph/search-core
                  team/code-insights=@joelkw @felixfbecker @vovakulikov @unclejustin
                  team/delivery=@sourcegraph/delivery
                  team/security=@dcomas
                  team/dev-experience=@jhchabran @kstretch9
                  team/frontend-platform=@taylorsperry @muratsu
                  team/repo-management=@jplahn @ryphil
                  team/devops=@sourcegraph/cloud-devops
                  team/iam=@sourcegraph/iam
