name: "Notify users based on issue labels"

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: felixfbecker/issue-label-notification-action@57b8a1f93c7951ce8af6cce8c6c90ae35a51c2e0
          with:
             token: "${{ secrets.LABELER_GITHUB_TOKEN }}"
             edit_body: true
             message: /cc {recipients}
             recipients: |
                  team/growth=@sourcegraph/growth
                  team/cloud=@sourcegraph/cloud
                  team/search-product=@sourcegraph/search-product
                  team/search-core=@sourcegraph/search-core
                  team/code-insights=@vovakulikov
                  team/security=@dcomas
                  team/dev-experience=@jhchabran @kstretch9
                  team/devops=@sourcegraph/cloud-devops
                  cody-gateway=@unknwon @eseliger @bobheadxi @rafax
                  team/search-platform=@sourcegraph/search-platform
