name: "Notify users based on issue labels"

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@f7d2363e5efa18b8aeea671ca8093e183ae8f218 # 1.3
          with:
             token: "${{ secrets.LABELER_GITHUB_TOKEN }}"
             recipients: |
                  team/integrations=@muratsu @jjinnii @ryankscott
                  team/growth=@muratsu @a-bergevin
                  team/cloud=@RafLeszczynski
                  team/search-product=@benvenker @lguychard
                  team/search-core=@jjeffwarner
                  [deprecated]team/search=@lguychard @benvenker @jjeffwarner
                  team/code-insights=@joelkw @felixfbecker @vovakulikov @unclejustin
                  team/distribution=@dan-mckean
                  team/delivery=@caugustus-sourcegraph @kevinwojo @michaellzc
                  team/security=@dcomas
                  team/dev-experience=@taylorsperry @jhchabran @kstretch9
                  team/repo-management=@jplahn
                  team/devops=@sourcegraph/cloud-devops
                  team/iam-admin-experience=@sourcegraph/iam-and-admin-experience
