name: Licenses Check
on: [ pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with: { ruby-version: '2.6' }
    - uses: actions/setup-go@v2
      with: { go-version: '1.14' }
    - uses: actions/setup-node@v1
      with: { node-version: '14.4' }

    - name: Install license_finder
      run: gem install license_finder
    - name: Prepare dependencies
      run: |
        yarn --mutex network --frozen-lockfile
        go mod vendor

    - name: Check dependencies
      run: LICENSE_CHECK=true ./dev/licenses.sh
