name: lsif-ts
on:
  push:
    paths:
      - '**.ts'
      - '**.js'

jobs:
  lsif-tsc-eslint:
    # Skip running on forks
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-node
    env:
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      NODE_OPTIONS: --max_old_space_size=5120
    strategy:
      matrix:
        root:
          - client/branded
          - client/browser
          - client/build-config
          - client/shared
          - client/web
          - client/wildcard
          - client/common
          - client/http-client
          - client/codeintellify
          - client/template-parser
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: apk --no-cache add python g++ make git
      - name: Install dependencies
        run: yarn --ignore-engines --ignore-scripts
      - name: Run gulp generate
        run: ./node_modules/.bin/gulp generate

      # Run lsif-tsc
      - name: Run lsif-tsc
        working-directory: ${{ matrix.root }}
        run: lsif-tsc -p .

      # Upload lsif-tsc data to Cloud, Dogfood, and Demo instances
      - name: Upload lsif-tsc dump to Cloud
        working-directory: ${{ matrix.root }}
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
      - name: Upload lsif-tsc dump to Dogfood
        working-directory: ${{ matrix.root }}
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
        env:
          SRC_ENDPOINT: https://k8s.sgdev.org/
      - name: Upload lsif-tsc dump to Demo
        working-directory: ${{ matrix.root }}
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
        env:
          SRC_ENDPOINT: https://demo.sourcegraph.com/

      # Run lsif-eslint
      - name: Build TypeScript
        run: yarn run --ignore-engines build-ts
      - name: Run lsif-eslint
        working-directory: ${{ matrix.root }}
        run: yarn eslint -f lsif

      # Upload lsif-eslint data to Cloud, Dogfood, and Demo instances
      - name: Upload lsif-eslint dump to Cloud
        working-directory: ${{ matrix.root }}
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
      - name: Upload lsif-eslint dump to Dogfood
        working-directory: ${{ matrix.root }}
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
        env:
          SRC_ENDPOINT: https://k8s.sgdev.org/
      # - name: Upload lsif-eslint dump to Demo
      #   working-directory: ${{ matrix.root }}
      #   run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
      #   env:
      #     SRC_ENDPOINT: https://demo.sourcegraph.com/
