name: LSIF
on:
  - push
jobs:
  lsif-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate LSIF data
        uses: sourcegraph/lsif-go-action@master
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  lsif-web:
    runs-on: ubuntu-latest
    container: node:13.8.0-alpine3.10
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: apk --no-cache add python g++ make git
      - name: Install dependencies
        run: yarn
      - name: Generate LSIF data
        uses: sourcegraph/lsif-node-action@master
        with:
          project_root: web
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          root: web
          github_token: ${{ secrets.GITHUB_TOKEN }}

  lsif-lsif:
    runs-on: ubuntu-latest
    container: node:13.8.0-alpine3.10
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn --cwd lsif
      - name: Generate LSIF data
        uses: sourcegraph/lsif-node-action@master
        with:
          project_root: lsif
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          root: lsif
          github_token: ${{ secrets.GITHUB_TOKEN }}

  lsif-shared:
    runs-on: ubuntu-latest
    container: node:13.8.0-alpine3.10
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: apk --no-cache add python g++ make git
      - name: Install dependencies
        run: yarn
      - name: Generate LSIF data
        uses: sourcegraph/lsif-node-action@master
        with:
          project_root: shared
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          root: shared
          github_token: ${{ secrets.GITHUB_TOKEN }}

  lsif-browser:
    runs-on: ubuntu-latest
    container: node:13.8.0-alpine3.10
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: apk --no-cache add python g++ make git
      - name: Install dependencies
        run: yarn
      - name: Generate LSIF data
        uses: sourcegraph/lsif-node-action@master
        with:
          project_root: browser
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          root: browser
          github_token: ${{ secrets.GITHUB_TOKEN }}
