name: Move labled issues to Project

on:
  issues:
    types:
      - opened
      - labeled
      - transferred

jobs:
  add-to-project-beta:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Move team/devops or team/cloud issues
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/sourcegraph/projects/264
          github-token: ${{ secrets.GH_PROJECTS_ACTION_TOKEN }}
          labeled: team/cloud
          label-operator: OR

      - name: Move team/code-exploration issues
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/sourcegraph/projects/297
          github-token: ${{ secrets.GH_PROJECTS_ACTION_TOKEN }}
          labeled: team/code-exploration
          label-operator: OR

      - name: Move design issues
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/sourcegraph/projects/278
          github-token: ${{ secrets.GH_PROJECTS_ACTION_TOKEN }}
          labeled: design, needs-design
          label-operator: OR

      - name: Move team/code-insights issues
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/sourcegraph/projects/291
          github-token: ${{ secrets.GH_PROJECTS_ACTION_TOKEN }}
          labeled: team/code-insights
          label-operator: OR

      - name: Move cody issues
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/sourcegraph/projects/331
          github-token: ${{ secrets.GH_PROJECTS_ACTION_TOKEN }}
          labeled: cody
          label-operator: OR

#       - name: Move team/CHANGEME issues
#         uses: actions/add-to-project@main
#         with:
#           project-url: https://github.com/orgs/sourcegraph/projects/CHANGEME
#           github-token: ${{ secrets.GH_PROJECTS_ACTION_TOKEN }}
#           labeled: team/CHANGEME
#           label-operator: OR
