# See https://docs.sourcegraph.com/dev/background-information/ci#pr-auditor
name: pr-auditor
on:
  pull_request_target:
    types: [ closed, edited, opened, synchronize, ready_for_review ]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { repository: 'sourcegraph/sourcegraph', ref: '03-17-dev/pr-auditor_use_labels_to_exempt_from_review' }
      - uses: actions/setup-go@v2
        with: { go-version: '1.19' }

      - run: ./dev/pr-auditor/check-pr.sh
        env:
          GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
          GITHUB_TOKEN: ${{ secrets.CODENOTIFY_GITHUB_TOKEN }}
          GITHUB_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
