name: pr-auditor
on:
  pull_request_target:
    types: [ closed, edited, opened, synchronize, ready_for_review ]


jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'sourcegraph/devx-service'
          token: ${{ secrets.PR_AUDITOR_TOKEN }}
      - uses: actions/setup-go@v4
        with: { go-version: '1.22' }

      - run: 'go run ./cmd/pr-auditor'
        env:
          GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
          GITHUB_TOKEN: ${{ secrets.PR_AUDITOR_TOKEN }}
          GITHUB_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
  report_failure:
    needs: check-pr
    if: ${{ failure() }}
    uses: sourcegraph/sourcegraph/.github/workflows/report-job-failure.yml@main
    secrets: inherit
