name: Changelog progress
on:
  schedule:
  - cron: "0 1 * * 6"   # Every Saturday 1:00am UTC (Friday 5pm PST)
  push:
    branches:
      - main
      - master
jobs:
  sync-progress-channel:
    runs-on: ubuntu-latest
    name: Sync changelog to progress channel
    env:
      WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PROGRESS_CHANNEL }}
      # # Replace with this URL for testing:
      # WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST_CHANNEL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: ./dev/report_progress_to_slack.py
        shell: bash
