on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
      workflow_name:
        required: true
        type: string
      job_name:
        required: false
        type: string
      run_id:
        required: true
        type: string

jobs:
  send_failure_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - name: Send Sentry event for failed action
        run: |
          MSG="A Job in the ${{ inputs.workflow_name }} action has failed - see run for exact failure"
          if [[ -z "${{ inputs.job_name }}" ]]; then
            MSG="The Job '${{ inputs.job_name }}' in the ${{ inputs.workflow_name }} action has failed - see run for exact failure"
          fi
          npm i -g @sentry/cli
          sentry-cli send-event -m "${MSG}" \
            -t "github-action:${{ inputs.workflow_name }}" \
            -t "branch:${{ inputs.branch }}" \
            -t "repository:${{ inputs.repo }}" \
            -t "workflow-run: https://github.com/${{ inputs.repo }}/actions/runs/${{ inputs.run_id }}" \
            --no-environ
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DEV_INFRA_DSN }}
          SENTRY_ORG: sourcegraph
          SENTRY_PROJECT: dev-infra
