name: scip-typescript
on:
  push:
    paths:
      - '**.ts'
      - '**.js'

jobs:
  scip-typescript:
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn --ignore-engines --ignore-scripts
      - run: yarn global add @sourcegraph/scip-typescript
      - run: scip-typescript index --yarn-workspaces
      - run: cp index.scip dump.lsif-typed
      - name: Install src-cli
        run: |
          curl -L https://sourcegraph.com/.api/src-cli/src_linux_amd64 -o /usr/local/bin/src
          chmod +x /usr/local/bin/src
      - name: Upload SCIP to Cloud
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
      - name: Upload lsif to Dogfood
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
        env:
          SRC_ENDPOINT: https://k8s.sgdev.org/
      - name: Upload lsif to Demo
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
        env:
          SRC_ENDPOINT: https://demo.sourcegraph.com/
