name: Tracking Issue Syncer
on:
  schedule:
    - cron:  '*/15 * * * *'
  issues:
    types:
    - opened
    - edited
    - deleted
    - closed
    - reopened
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - milestoned
    - demilestoned
jobs:
  core-services:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://sourcegraph/tracking-issue:latest
        with:
          args: -milestone 3.15 -labels team/core-services -update
        env:
          GITHUB_TOKEN: ${{ secrets.TRACKING_ISSUE_SYNCER_TOKEN }}
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://sourcegraph/tracking-issue:latest
        with:
          args: -milestone 3.15 -labels team/web -update
        env:
          GITHUB_TOKEN: ${{ secrets.TRACKING_ISSUE_SYNCER_TOKEN }}
