name: universal-ctags

on:
  push:
    paths:
      - 'dev/nix/ctags.nix'
    branches:
        - 'main'
  pull_request:
    paths:
      - 'dev/nix/ctags.nix'
  workflow_dispatch:
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  x86_64-darwin:
    name: Build ctags x86_64-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - id: auth
        name: 'ðŸ”“ Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.CTAGS_GCP_SERVICE_ACCOUNT }}
      - id: nix-build
        name: Run `nix build`
        run: |
          nix build .#ctags
          sudo codesign --force -s - ./result/bin/universal-ctags-*
      - id: 'rename-and-upload'
        name: Rename an prepare for upload
        run: |
          mkdir -p dist
          cp -R -L ./result/bin/universal-ctags-* dist/
          cd dist/ && ls | xargs -I{} mv {} "{}.$(git rev-parse --short HEAD)"
      - id: 'show-hash'
        name: Show hash of ctags
        run: |
          shasum -a 256 ./dist/universal-ctags-*
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        # github.head_ref is only available for pull requests
        # if the event type is not pull_requet we have to use github.ref_name
        if: ${{ github.ref_name == 'main' }}
        with:
          path: './dist/'
          destination: 'universal_ctags/x86_64-darwin/'
          glob: 'universal-ctags-*'
  aarch64-darwin:
    name: Build ctags aarch64-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - id: auth
        name: 'ðŸ”“ Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.CTAGS_GCP_SERVICE_ACCOUNT }}
      - id: nix-build
        name: Run `nix build`
        run: |
          nix build .#ctags-aarch64-darwin
          sudo codesign --force -s - ./result/bin/universal-ctags-*
      - id: 'rename-and-upload'
        name: Rename an prepare for upload
        run: |
          mkdir -p dist
          cp -R -L ./result/bin/universal-ctags-* dist/
          cd dist/ && ls | xargs -I{} mv {} "{}.$(git rev-parse --short HEAD)"
      - id: 'show-hash'
        name: Show hash of ctags
        run: |
          shasum -a 256 ./dist/universal-ctags-*
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        # github.head_ref is only available for pull requests
        # if the event type is not pull_requet we have to use github.ref_name
        if: ${{ github.ref_name == 'main' }}
        with:
          path: './dist/'
          destination: 'universal_ctags/aarch64-darwin'
          glob: 'universal-ctags-*'
  x86_64-linux:
    name: Build ctags x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - id: auth
        name: 'ðŸ”“ Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.CTAGS_GCP_SERVICE_ACCOUNT }}
      - id: nix-build
        name: Run `nix build`
        run: |
          exit 1
          nix build .#ctags
      - id: 'rename-and-upload'
        name: Rename an prepare for upload
        run: |
          mkdir -p dist
          cp -R -L ./result/bin/universal-ctags-* dist/
          cd dist/ && ls | xargs -I{} mv {} "{}.$(git rev-parse --short HEAD)"
      - id: 'show-hash'
        name: Show hash of ctags
        run: |
          shasum -a 256 ./dist/universal-ctags-*
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        # github.head_ref is only available for pull requests
        # if the event type is not pull_requet we have to use github.ref_name
        if: ${{ github.ref_name == 'main' }}
        with:
          path: './dist/'
          destination: 'universal_ctags/x86_64-linux'
          glob: 'universal-ctags-*'
      - name: report failure to sentry
        if: ${{ failure() }}
        run: |
          npm i -g @sentry/cli
          sentry-cli send-event -m "$GITHUB_WORKFLOW action failure - see run for exact failure" \
            -t "github-action:$GITHUB_WORKFLOW" \
            -t "branch:$GITHUB_REF_NAME" \
            -t "repository:$GITHUB_REPOSITORY" \
            -t "workflow-run:$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DEV_INFRA_DSN }}
          SENTRY_ORG: sourcegraph
          SENTRY_PROJECT: dev-infra
